font_family      FiraCode Nerd Font
bold_font        FiraCode Nerd Font
italic_font      FiraCode Nerd Font
bold_italic_font FiraCode Nerd Font
font_size 17.0

tab_bar_edge top
tab_bar_style powerline
tab_powerline_style slanted
tab_bar_min_tabs 1
tab_title_template          {title}{' ({})'.format(num_windows) if num_windows > 1 else ''}

shell /opt/homebrew/bin/bash --login

# Open windows, tabs and os windows with cwd
map kitty_mod+enter launch --cwd=current --type=window
map cmd+enter       launch --cwd=current --type=window
map kitty_mod+t     launch --cwd=current --type=tab
map cmd+t           launch --cwd=current --type=tab

# A bit of a border between windows
window_border_width 3.0pt

# Nicer scrolling
map shift+page_up scroll_page_up
map shift+page_down scroll_page_down
map shift+home scroll_home
map shift+end scroll_end

# switch between tall and stack
# Tall:
# ┌──────────────┬───────────────┐
# │              │               │
# │              │               │
# │              │               │
# │              ├───────────────┤
# │              │               │
# │              │               │
# │              │               │
# │              ├───────────────┤
# │              │               │
# │              │               │
# │              │               │
# └──────────────┴───────────────┘
enabled_layouts tall,stack
map kitty_mod+z toggle_layout stack

# Resize windows

map alt+shift+left resize_window narrower
map alt+shift+right resize_window wider
map alt+shift+up resize_window taller
map alt+shift+down resize_window shorter 3
# reset all windows in the tab to default sizes
map alt+shift+home resize_window reset

# Dim inactive panels
inactive_text_alpha 0.4

# run "kitty +kitten themes"
# BEGIN_KITTY_THEME
# Catppuccin-Macchiato
include current-theme.conf
# END_KITTY_THEME

# Kitty + neovim
# https://github.com/mikesmithgh/kitty-scrollback.nvim
allow_remote_control yes
listen_on unix:/tmp/kitty
shell_integration enabled

# Generated with nvim --headless +'KittyScrollbackGenerateKittens'
# kitty-scrollback.nvim Kitten alias
action_alias kitty_scrollback_nvim kitten /Users/eduardo.gurgelpinho/.local/share/nvim/lazy/kitty-scrollback.nvim/python/kitty_scrollback_nvim.py

# Browse scrollback buffer in nvim
map kitty_mod+h kitty_scrollback_nvim
# Browse output of the last shell command in nvim
map kitty_mod+g kitty_scrollback_nvim --config ksb_builtin_last_cmd_output
# Show clicked command output in nvim
mouse_map ctrl+shift+right press ungrabbed combine : mouse_select_command_output : kitty_scrollback_nvim --config ksb_builtin_last_visited_cmd_output
