return {
  'tpope/vim-unimpaired',
  'tpope/vim-surround',
  'tpope/vim-repeat',
  'tpope/vim-eunuch',
  'tpope/vim-fugitive',
  'tpope/vim-rhubarb',
  'ap/vim-css-color',
  'Raimondi/delimitMate',
  'sickill/vim-pasta',
  'mjbrownie/swapit',
  'airblade/vim-rooter',
  'ntpeters/vim-better-whitespace',
  'danilamihailov/beacon.nvim',
  'vim-scripts/blockle.vim',
  { 'echasnovski/mini.move', version = '*' },
}
